package firok.spring.mvci.comment;

/**
 * @since 17.2.0
 */
@SuppressWarnings("all")
public final class CurrentMapperNames
{
	private CurrentMapperNames() throws InstantiationException { throw new InstantiationException("不允许初始化"); }



	/**
	 * <p>当前项目中由 MVCI 生成的所有实体类 Mapper 完整限定名</p>
	 * <p>An array contains full qualified names of all mapper-class generated by MVCI</p>
	 *
	 * @implNote 此字段会在编译期填充内容 this field will be filled during compiling phase
	 */
	public static final String[] NAMES = new String[] {};



	/**
	 * <p>从类完整限定名获取对应 Mapper 的完整限定名</p>
	 * <p>To get full qualified name of mapper-class by full qualified name of bean-class</p>
	 *
	 * @param fullQualifiedBeanName 类完整限定名
	 * @return Mapper 完整限定名
	 * @implNote 此方法会在编译期填充内容 this method will be filled during compiling phase
	 */
	public static String getByFullQualifiedBeanName(String fullQualifiedBeanName)
	{
		return switch (fullQualifiedBeanName)
		{
			default -> null;
		};
	}
}
